name: Reusable workflow 1
on: 
  workflow_call:
  push:
    branches: [ master ]

jobs:
  ru1-job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name : write someting to log
        run: |
          echo "I am Anil"
