name: APOSNF-LOIS-QS
on:
  workflow_dispatch: null
  push:
    branches:
      - main
permissions:
  contents: write
env:
 ENVIRONMENT: 'dev'
jobs:
 SmokeTest:
    runs-on: ubuntu-latest
    steps:
      - name: Call environment-specific workflow
        if: env.ENVIRONMENT == 'dev'
        uses: ./.github/workflows/reusableworkflow.yml
      - name: Job Done
        run: echo "Done"
